change install.sh
Technomatix/ansible pull request #1
Opened 2017-08-28 12:52 UTC by Dreamlol

2017-08-28 13:17 UTC, ilyar approved these changes
Требуется пояснения

2017-08-28 13:17 UTC, ilyar commented on install.sh
> +#!/usr/bin/bash
если нет причин надо вернуть

2017-08-28 13:17 UTC, ilyar commented on install.sh
> +	wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg
просто поясни зачем это? `Install soft` не информативно, я потом сам оформлю

2017-08-28 13:17 UTC, ilyar commented on install.sh
> +	gcc-core gcc-g++ \
я правильно понимаю это нужно только для установки, для рантайма нет потребности и мы можем это удалить после успешного завершения процесса?

2017-08-28 13:24 UTC, Dreamlol commented on install.sh
> +	gcc-core gcc-g++ \
все что касается питона нужно для рантайма, остальное можно удалить

2017-08-28 13:25 UTC, Dreamlol commented on install.sh
> +	wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg
обычный комент для лучшей визуализации кода

2017-08-28 13:26 UTC, Dreamlol commented on install.sh
> +#!/usr/bin/bash
причин нет, можно вернуть

2017-08-28 16:01 UTC, ilyar requested changes

2017-08-28 16:01 UTC, ilyar commented on install.sh
> +if [ ${machine} = Linux ] ; then   # install for debian based system
надо поправить ошибки синтаксиса https://travis-ci.org/Technomatix/ansible/builds/269181008#L458-L460

2017-08-28 16:01 UTC, ilyar commented on install.sh
> +elif [ ${machine} = Cygwin ] ; then		# install for windows system
надо поправить ошибки синтаксиса https://travis-ci.org/Technomatix/ansible/builds/269181008#L463-L465

2017-08-28 16:01 UTC, ilyar commented on install.sh
> +#!/usr/bin/bash
тогда возвращай

2017-08-29 09:31 UTC, ilyar requested changes

2017-08-29 09:31 UTC, ilyar commented on install.sh
> +	wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg
комментарии это хорошо и правильно, но они должны пояснять и отвечать на вопросы, а не порождать новые, полагаю в данном случае он может быть `# Install package manager for ...`

2024-02-19 12:31 UTC, closed without merging